### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by amirovo** [5h4d0wb0y/socialbrute#2]
**i did [git clone git://github.com/5h4d0wb0y/socialbrute]
then [python setup.py install]**

socialbrute -help
Traceback (most recent call last):
  File "/usr/local/bin/socialbrute", line 11, in <module>
    load_entry_point('socialbrute==1.0.0', 'console_scripts', 'socialbrute')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/socialbrute-1.0.0-py2.7.egg/socialbrute/cli.py", line 9, in <module>
    import socialbrute
  File "/usr/local/lib/python2.7/dist-packages/socialbrute-1.0.0-py2.7.egg/socialbrute/socialbrute.py", line 8, in <module>
    from .modules.facebook import Facebook
ImportError: No module named modules.facebook

**then i installed it with python3 still gives me error**

Traceback (most recent call last):
  File "/usr/local/bin/socialbrute", line 11, in <module>
    load_entry_point('socialbrute==1.0.0', 'console_scripts', 'socialbrute')()
  File "/usr/local/lib/python3.7/dist-packages/setuptools-33.1.1-py3.7.egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "/usr/local/lib/python3.7/dist-packages/setuptools-33.1.1-py3.7.egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "/usr/local/lib/python3.7/dist-packages/setuptools-33.1.1-py3.7.egg/pkg_resources/__init__.py", line 2291, in load
  File "/usr/local/lib/python3.7/dist-packages/setuptools-33.1.1-py3.7.egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/local/lib/python3.7/dist-packages/socialbrute-1.0.0-py3.7.egg/socialbrute/cli.py", line 10, in <module>
    from socialbrute.socialbrute import *
  File "/usr/local/lib/python3.7/dist-packages/socialbrute-1.0.0-py3.7.egg/socialbrute/socialbrute.py", line 8, in <module>
    from .modules.facebook import Facebook
ModuleNotFoundError: No module named 'socialbrute.modules'

**Comment by w1l5t3r** [comment]
chmod_x setup/py
pip install -r requirements_dev.txt

then all good to go

**Comment by amirovo** [comment]
chmod -x setup.py
pip install -r requirements_dev.txt
python setup.py install

**did not work 
still get this error**

 from .modules.facebook import Facebook
ImportError: No module named modules.facebook

**Comment by 5h4d0wb0y** [comment]
The import of social network modules was missing. Try it now.
