### ISSUE TITLE
TypeError: main() missing 1 required positional argument: 'token'

### ISSUE THREAD

**Issue by juanith0o** [5h4d0wb0y/socialbrute#4]
* socialbrute version:1.0.2
* Python version:3
* Operating System: Parro OS

### Description

When I throw socialbrute appear to me this message. I try it as user and root and give me this 

```
──╼ #socialbrute
Traceback (most recent call last):
  File "/usr/local/bin/socialbrute", line 11, in <module>
    load_entry_point('socialbrute==1.0.2', 'console_scripts', 'socialbrute')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: main() missing 1 required positional argument: 'token'

```

**Comment by 5h4d0wb0y** [comment]
Problem solved with the new release.
